[package]
name = "onitama"
version = "0.1.0"
edition = "2021"

[dependencies]
# sdl2 = { version = "0.36.0", features = ["gfx", "image"] }
sdl2 = { version = "0.36.0", features = ["image", "mixer"] }
tinyrand = "0.5.0"
tinyrand-std = "0.5.0"
